{% set name = "blis" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flame/blis/archive/{{ version }}.tar.gz
  sha256: 9c7efd75365a833614c01b5adfba93210f869d92e7649e0b5d9edc93fc20ea76

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev               # [win or osx]
    - posix                  # [win]
    - m2-sed                 # [win]
    - sed                    # [unix]
    - perl
    - python >=3.5
  host:
    - pthreads-win32         # [win]
  run:
    - pthreads-win32         # [win]

test:
  commands:
    - test -f $PREFIX/lib/libblis.a                       # [unix]
    - test -f $PREFIX/lib/libblis${SHLIB_EXT}             # [unix]
    - test -f $PREFIX/include/blis/blis.h                 # [unix]
    - test -f $PREFIX/include/blis/cblas.h                # [unix]
    - if not exist %LIBRARY_INC%\\blis\\blis.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\blis\\cblas.h exit 1    # [win]
    - if not exist %LIBRARY_LIB%\\blis.lib exit 1         # [win]

about:
  home: http://github.com/flame/blis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'BLAS-like Library Instantiation Software Framework'

extra:
  recipe-maintainers:
    - isuruf
