travis:
  secure:
    BINSTAR_TOKEN: Pw182HN/G/avykbZ0H9IhSEhG5k8V+qp38MgiMky2XwzC6CwwjwF8qidFvOCG4snpHgqJfaCRCe0NWPBECyLlJRfYVRUn6cfixSpHeOy7r+iR9EGcZ2w7sfGq8h4D82jAMOly8KUfa/FPOrgV1xp0a/BVdFORy5PgqzgK0b4bTkF7/2RK/BavuEjXbLEqmtszX9/Mx0TZ4Ds3m0p1rHheCV5pJe10OMKvN+2sEvJrqxLbFEwKgHd/n1fyX+i2VNZNKVe9Fw6irue0MOUjcND50u6CceeXKJGFrMJdnOrRiPtppAAiwsgGnslioFEOzrRqxHZ/ggaIatwtq6LfK8B6wXPu0nCPBbYDNo8IPdKQs1M1CRp/Kd7dqEPHMy5O8T/z6omFKDlaRB9cbI8fg2ksjhO06JKQ/+bwww+7B3subgUOImcq8s8I7bTp2fQuz8Xl6CCtKg/bz/IcrBObZ72g2JSs0yHvVjH5vC/3tm6w4ufqYaFzf88iM0E5iKFGTADmAsfwyqrEMcKSnZzdVjTHMlGH3Tcvjx3MthAQj93gmGuR2qLVHdZce6s3VeYSHGKkBs2Jegi85Xg91JlD9+bY0hK3UwBC+vKMAgcdOWo8gOR4skXgVozzVIMU+ryaKqUg6pLyUS1Ldh5xlQ6peAVouAXbUwrVZMt21MKmVv959M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
